apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  pre-flight:
    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: Log into AWS
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-to-assume: infra-admin
          role-duration-seconds: "3600"
          aws-session-token: $ {{ secrets.aws_session_token }}
      - uses: docker://golang:1.20.3-alpine3.17
        name: Finish Script
        shell: sh
        run: |
          echo "We Are Done"
