apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  pre-flight:
    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: Log into AWS
        with:
          aws-region: us-east-1
          role-to-assume: infra-admin
          role-duration-seconds: "3600"
      - uses: docker://golang:1.20.3-alpine3.17
        name: Finish Script
        shell: sh
        run: |
          echo "We Are Done"
