apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  prep-env:
    environment: ""
    steps:
      - uses: cloudbees-io/configure-aws-credentials@v1
        name: Log into AWS
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          role-duration-seconds: "3600"
      - uses: docker://releases-docker.jfrog.io/jfrog/jfrog-cli-v2-jf
        name: jf cli
        run: jf -v
  appApproval:
    timeout-minutes: 4320
    delegates: cloudbees-io/manual-approval/custom-job.yml@v1
    with:
      approvers: b27862d0-fb9a-11eb-afae-42010a83ae52
      disallowLaunchByUser: false
      instructions: ""
    needs: prep-env
  pre-flight:
    steps:
      - uses: cloudbees-io/s3-download-object@v1
        name: Retrieve Maven Cache
        with:
          bucket-name: cwroble-caching-demo
          file-path: petclinic-v3.3.4.tar.gz
          s3-path: platform-cache/maven/petclinic-v3.3.4.tar.gz
      - uses: docker://golang:1.20.3-alpine3.17
        name: Finish Script
        shell: sh
        run: |
          ls -l
          echo "We Are Done"
    needs: appApproval

